IF NOT EXISTS (SELECT 1 FROM TipUplate)
BEGIN
	SET IDENTITY_INSERT [dbo].[Opcina] ON 

	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (1, N'Berkovići')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (2, N'Osmaci')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (3, N'Oštra Luka')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (4, N'Pale (FBiH)')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (5, N'Pale (RS)')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (6, N'Pelagićevo')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (7, N'Petrovac')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (8, N'Orašje')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (9, N'Petrovo')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (10, N'Prijedor')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (11, N'Prnjavor')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (12, N'Prozor-Rama')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (13, N'Ravno')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (14, N'Ribnik')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (15, N'Rogatica')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (16, N'Posušje')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (17, N'Rudo')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (18, N'Olovo')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (19, N'Novo Sarajevo')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (20, N'Lukavac')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (21, N'Ljubinje')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (22, N'Ljubuški')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (23, N'Maglaj')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (24, N'Milići')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (25, N'Modriča')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (26, N'Odžak')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (27, N'Mostar')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (28, N'Neum')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (29, N'Nevesinje')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (30, N'Novi Grad')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (31, N'Novi Grad (Sarajevo)')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (32, N'Novi Travnik')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (33, N'Novo Goražde')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (34, N'Mrkonjić Grad')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (35, N'Sanski Most')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (36, N'Sapna')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (37, N'Sarajevo')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (38, N'Tuzla')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (39, N'Ugljevik')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (40, N'Usora')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (41, N'Vareš')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (42, N'Velika Kladuša')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (43, N'Visoko')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (44, N'Trnovo (RS)')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (45, N'Višegrad')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (46, N'Vlasenica')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (47, N'Vogošća')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (48, N'Vukosavlje')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (49, N'Zavidovići')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (50, N'Zenica')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (51, N'Zvornik')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (52, N'Vitez')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (53, N'Trnovo (FBiH)')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (54, N'Trebinje')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (55, N'Travnik')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (56, N'Sokolac')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (57, N'Srbac')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (58, N'Srebrenica')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (59, N'Srebrenik')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (60, N'Stanari')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (61, N'Stari Grad')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (62, N'Stolac')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (63, N'Šamac')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (64, N'Šekovići')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (65, N'Šipovo')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (66, N'Široki Brijeg')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (67, N'Teočak')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (68, N'Teslić')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (69, N'Tešanj')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (70, N'Tomislavgrad')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (71, N'Lopare')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (72, N'Žepče')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (73, N'Livno')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (74, N'Kupres (RS)')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (75, N'Čapljina')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (76, N'Čelić')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (77, N'Čelinac')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (78, N'Čitluk')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (79, N'Derventa')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (80, N'Doboj')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (81, N'Čajniče')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (82, N'Doboj-Istok')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (83, N'Dobretići')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (84, N'Domaljevac-Šamac')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (85, N'Donji Vakuf')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (86, N'Donji Žabar')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (87, N'Drvar')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (88, N'Foča (FBiH)')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (89, N'Doboj-Jug')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (90, N'Foča (RS)')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (91, N'Centar')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (92, N'Bužim')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (93, N'Banja Luka')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (94, N'Banovići')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (95, N'Bihać')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (96, N'Bijeljina')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (97, N'Bileća')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (98, N'Bosanska Krupa')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (99, N'Cazin')

	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (100, N'Bosanski Petrovac')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (101, N'Bratunac')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (102, N'Brčko')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (103, N'Breza')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (104, N'Brod')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (105, N'Bugojno')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (106, N'Busovača')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (107, N'Bosansko Grahovo')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (108, N'Fojnica')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (109, N'Gacko')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (110, N'Glamoč')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (111, N'Kakanj')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (112, N'Kalesija')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (113, N'Kalinovik')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (114, N'Kiseljak')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (115, N'Kladanj')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (116, N'Ključ')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (117, N'Jezero')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (118, N'Kneževo')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (119, N'Kostajnica')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (120, N'Kotor-Varoš')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (121, N'Kozarska Dubica')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (122, N'Kreševo')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (123, N'Krupa na Uni')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (124, N'Kupres (FBiH)')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (125, N'Konjic')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (126, N'Jajce')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (127, N'Jablanica')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (128, N'Istočno Sarajevo')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (129, N'Goražde')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (130, N'Gornji Vakuf-Uskoplje')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (131, N'Gračanica')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (132, N'Gradačac')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (133, N'Gradiška')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (134, N'Grude')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (135, N'Hadžići')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (136, N'Han-Pijesak')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (137, N'Ilidža')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (138, N'Ilijaš')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (139, N'Istočna Ilidža')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (140, N'Istočni Drvar')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (141, N'Istočni Mostar')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (142, N'Istočni Stari Grad')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (143, N'Istočno Novo Sarajevo')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (144, N'Laktaši')
	INSERT [dbo].[Opcina] ([Id], [Naziv]) VALUES (145, N'Živinice')
	SET IDENTITY_INSERT [dbo].[Opcina] OFF

	
	SET IDENTITY_INSERT [dbo].[ApplicationUser] ON 
	INSERT [dbo].[ApplicationUser] ([Id], [Email], [Username], [PasswordHash], [PasswordSalt], [Slika], [Ime], [Prezime], [DatumRodjenja], [OpcinaId], [JMBG], [Spol], [DatumRegistracije], [Active]) VALUES (1, N'osoblje@user.com', N'administrativnoOsoblje', N'Qx+8APMxTi+3z7rAi4cr7w==', N'4MDzEbW7FZxGG0kEoSy8dg==', NULL, N'Charlie', N'Rogers', CAST(N'1995-01-01T00:00:00.0000000' AS DateTime2), 1, N'1111111111111', N'M', CAST(N'2020-06-10T23:04:30.6670480' AS DateTime2), 1)
	SET IDENTITY_INSERT [dbo].[ApplicationUser] OFF

	
	SET IDENTITY_INSERT [dbo].[Uposlenik] ON 

	INSERT [dbo].[Uposlenik] ([Id], [ApplicationUserId], [DatumZaposlenja]) VALUES (1, 1, CAST(N'2020-06-10T23:04:30.7563075' AS DateTime2))
	SET IDENTITY_INSERT [dbo].[Uposlenik] OFF

	
	SET IDENTITY_INSERT [dbo].[Role] ON 

	INSERT [dbo].[Role] ([Id], [Naziv]) VALUES (1, N'AdministrativnoOsoblje')
	INSERT [dbo].[Role] ([Id], [Naziv]) VALUES (2, N'Predavač')
	INSERT [dbo].[Role] ([Id], [Naziv]) VALUES (3, N'Klijent')
	SET IDENTITY_INSERT [dbo].[Role] OFF

	INSERT [dbo].[ApplicationUserRole] ([ApplicationUserId], [RoleId]) VALUES (1, 1)
	SET IDENTITY_INSERT [dbo].[TipUplate] ON 

	INSERT [dbo].[TipUplate] ([Id], [Naziv], [Cijena]) VALUES (1, N'Jednokratna uplata za kurs', NULL)
	INSERT [dbo].[TipUplate] ([Id], [Naziv], [Cijena]) VALUES (2, N'Članarina', CAST(200.00 AS Decimal(18, 2)))
	SET IDENTITY_INSERT [dbo].[TipUplate] OFF
END